language: go
go:
  - 1.11.x
sudo: false
matrix:
  include:
  # Using vendored dependencies
  - install:
    - go get -u golang.org/x/lint/golint
    - go get -u golang.org/x/tools/cmd/...
    script:
    - export GO111MODULE=on
    - go mod download
    - go test -v -race $(go list ./...)
    - go vet $(go list ./...)
    - diff <(goimports -local github.com/ProtocolONE/chihaya -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
    - (for d in $(go list ./...); do diff <(golint $d) <(printf "") || exit 1;  done)
    - go install github.com/ProtocolONE/chihaya/cmd/chihaya
    - chihaya --config=example_config.yaml --debug&
    - pid=$!
    - sleep 2 # wait for chihaya to start up (gross)
    - chihaya e2e --debug
    - kill $pid
  # Using HEAD of dependencies
  - install:
    - go get -t ./...
    - go get -u golang.org/x/lint/golint
    - go get -u golang.org/x/tools/cmd/...
    script:
    - go test -v -race $(go list ./...)
    - go vet $(go list ./...)
    - diff <(goimports -local github.com/ProtocolONE/chihaya -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
    - (for d in $(go list ./...); do diff <(golint $d) <(printf "") || exit 1;  done)
    - go install github.com/ProtocolONE/chihaya/cmd/chihaya
    - chihaya --config=example_config.yaml --debug&
    - pid=$!
    - sleep 2 # wait for chihaya to start up (gross)
    - chihaya e2e --debug
    - kill $pid
  allow_failures:
  # Using HEAD of dependencies
  - install:
    - go get -t ./...
    - go get -u golang.org/x/lint/golint
    - go get -u golang.org/x/tools/cmd/...
    script:
    - go test -v -race $(go list ./...)
    - go vet $(go list ./...)
    - diff <(goimports -local github.com/ProtocolONE/chihaya -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
    - (for d in $(go list ./...); do diff <(golint $d) <(printf "") || exit 1;  done)
    - go install github.com/ProtocolONE/chihaya/cmd/chihaya
    - chihaya --config=example_config.yaml --debug&
    - pid=$!
    - sleep 2 # wait for chihaya to start up (gross)
    - chihaya e2e --debug
    - kill $pid
notifications:
  irc:
    channels:
    - irc.freenode.net#chihaya
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
  email: false
