{{- $deployment := .Values.backend -}}
{{- $svcName := printf "%s" .Release.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/"
    prometheus.io/port: {{ $v := .Values.config.chihaya.prometheus_addr | split ":" }}{{ $v._1 | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: restapi
    port: {{ $deployment.service.port }}
    targetPort: {{ $deployment.port }}
    protocol: {{ $deployment.service.protocol }} 
  - name: bittorrent-http
    port: {{ $v := .Values.config.chihaya.http.addr | split ":" }}{{ $v._1 }}
    targetPort: {{ $v := .Values.config.chihaya.http.addr | split ":" }}{{ $v._1 }}
    {{ if eq .Values.service.type "NodePort"}}
    nodePort: {{ .Values.service.tcpNodePort }}
    {{- end }}
    protocol: TCP
  - name: bittorrent-udp
    port: {{ $v := .Values.config.chihaya.udp.addr | split ":" }}{{ $v._1 }}
    targetPort: {{ $v := .Values.config.chihaya.udp.addr | split ":" }}{{ $v._1 }}
    {{ if eq .Values.service.type "NodePort"}}
    nodePort: {{ .Values.service.udpNodePort }}
    {{- end }}
    protocol: UDP
  - name: metrics
    port: {{ $v := .Values.config.chihaya.prometheus_addr | split ":" }}{{ $v._1 }}
    targetPort: {{ $v := .Values.config.chihaya.prometheus_addr | split ":" }}{{ $v._1 }}
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
